<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ABAsim>
  <Agents>
    <Agent>
      <SimId>6</SimId>
      <InternalId>6</InternalId>
      <Name>AgentWorker</Name>
      <Bounds>259,456,180,180</Bounds>
      <Reasoner>ManagerWorker</Reasoner>
      <UsePetriNet>false</UsePetriNet>
    </Agent>
    <Agent>
      <SimId>4</SimId>
      <InternalId>4</InternalId>
      <Name>AgentWorkstation</Name>
      <Bounds>2192,31,180,180</Bounds>
      <Reasoner>ManagerWorkstation</Reasoner>
      <ReasonerBounds>74,25,32,25</ReasonerBounds>
      <UsePetriNet>false</UsePetriNet>
    </Agent>
    <Agent>
      <SimId>5</SimId>
      <InternalId>5</InternalId>
      <Name>AgentMove</Name>
      <Bounds>1931,610,180,180</Bounds>
      <Reasoner>ManagerMove</Reasoner>
      <ReasonerBounds>74,25,32,25</ReasonerBounds>
      <UsePetriNet>false</UsePetriNet>
      <Components>
        <Process>
          <SimId>1005</SimId>
          <InternalId>42</InternalId>
          <Name>ProcessAgentMove</Name>
          <Bounds>38,136,35,18</Bounds>
        </Process>
        <Process>
          <SimId>1006</SimId>
          <InternalId>47</InternalId>
          <Name>ProcessAgentMoveStorage</Name>
          <Bounds>110,136,35,18</Bounds>
        </Process>
      </Components>
    </Agent>
    <Agent>
      <SimId>2</SimId>
      <InternalId>2</InternalId>
      <Name>AgentBoss</Name>
      <Bounds>638,-289,180,180</Bounds>
      <Reasoner>ManagerBoss</Reasoner>
      <UsePetriNet>false</UsePetriNet>
    </Agent>
    <Agent>
      <SimId>8</SimId>
      <InternalId>61</InternalId>
      <Name>AgentGroupB</Name>
      <Bounds>876,1511,180,180</Bounds>
      <Reasoner>ManagerGroupB</Reasoner>
      <UsePetriNet>false</UsePetriNet>
    </Agent>
    <Agent>
      <SimId>3</SimId>
      <InternalId>3</InternalId>
      <Name>AgentWorkplace</Name>
      <Bounds>1300,78,180,180</Bounds>
      <Reasoner>ManagerWorkplace</Reasoner>
      <UsePetriNet>false</UsePetriNet>
    </Agent>
    <Agent>
      <SimId>1</SimId>
      <InternalId>1</InternalId>
      <Name>AgentOkolie</Name>
      <Bounds>-111,92,180,180</Bounds>
      <Reasoner>ManagerOkolie</Reasoner>
      <ReasonerBounds>74,25,32,25</ReasonerBounds>
      <UsePetriNet>false</UsePetriNet>
      <Components>
        <Scheduler>
          <SimId>1001</SimId>
          <InternalId>17</InternalId>
          <Name>SchedulerOrderArrival</Name>
          <Bounds>73,141,35,13</Bounds>
        </Scheduler>
      </Components>
    </Agent>
    <Agent>
      <SimId>7</SimId>
      <InternalId>7</InternalId>
      <Name>AgentGroupA</Name>
      <Bounds>151,1285,180,180</Bounds>
      <Reasoner>ManagerGroupA</Reasoner>
      <ReasonerBounds>74,25,32,25</ReasonerBounds>
      <UsePetriNet>false</UsePetriNet>
      <Components>
        <Process>
          <SimId>1002</SimId>
          <InternalId>26</InternalId>
          <Name>ProcessCutting</Name>
          <Bounds>73,119,35,18</Bounds>
        </Process>
        <Process>
          <SimId>1008</SimId>
          <InternalId>51</InternalId>
          <Name>ProcessFitting</Name>
          <Bounds>26,119,35,18</Bounds>
        </Process>
        <Process>
          <SimId>1007</SimId>
          <InternalId>49</InternalId>
          <Name>ProcessPreparing</Name>
          <Bounds>123,119,35,18</Bounds>
        </Process>
      </Components>
    </Agent>
    <Agent>
      <SimId>10</SimId>
      <InternalId>67</InternalId>
      <Name>AgentGroupC</Name>
      <Bounds>1469,1379,180,180</Bounds>
      <Reasoner>ManagerGroupC</Reasoner>
      <UsePetriNet>false</UsePetriNet>
    </Agent>
  </Agents>
  <Messages>
    <Message>
      <SimId>1021</SimId>
      <InternalId>66</InternalId>
      <Name>RequestResponseMoveWorker</Name>
      <Type>RequestResponse</Type>
      <Source>61</Source>
      <Destination>6</Destination>
    </Message>
    <Message>
      <InternalId>68</InternalId>
      <Type>Parent</Type>
      <Source>67</Source>
      <Destination>6</Destination>
    </Message>
    <Message>
      <SimId>1023</SimId>
      <InternalId>71</InternalId>
      <Name>RequestResponseMoveWorker</Name>
      <Type>RequestResponse</Type>
      <Source>67</Source>
      <Destination>6</Destination>
    </Message>
    <Message>
      <SimId>1024</SimId>
      <InternalId>72</InternalId>
      <Name>RequestResponseWorkAgentC</Name>
      <Type>RequestResponse</Type>
      <Source>6</Source>
      <Destination>67</Destination>
    </Message>
    <Message>
      <SimId>1001</SimId>
      <InternalId>10</InternalId>
      <Name>NoticeInitAgentOkolie</Name>
      <Type>Notice</Type>
      <Source>2</Source>
      <Destination>1</Destination>
    </Message>
    <Message>
      <SimId>1002</SimId>
      <InternalId>11</InternalId>
      <Name>NoticeInitWorkplace</Name>
      <Type>Notice</Type>
      <Source>2</Source>
      <Destination>3</Destination>
    </Message>
    <Message>
      <InternalId>18</InternalId>
      <Type>StartFinish</Type>
      <Source>1</Source>
      <Destination>17</Destination>
    </Message>
    <Message>
      <SimId>1007</SimId>
      <InternalId>20</InternalId>
      <Name>NoticeOrderArrival</Name>
      <Type>Notice</Type>
      <Source>17</Source>
      <Destination>1</Destination>
    </Message>
    <Message>
      <SimId>1008</SimId>
      <InternalId>21</InternalId>
      <Name>RequestResponseOrderArrival</Name>
      <Type>RequestResponse</Type>
      <Source>1</Source>
      <Destination>2</Destination>
    </Message>
    <Message>
      <SimId>1009</SimId>
      <InternalId>24</InternalId>
      <Name>RequestResponseOrderArrived</Name>
      <Type>RequestResponse</Type>
      <Source>2</Source>
      <Destination>3</Destination>
    </Message>
    <Message>
      <InternalId>27</InternalId>
      <Type>StartFinish</Type>
      <Source>7</Source>
      <Destination>26</Destination>
    </Message>
    <Message>
      <SimId>1013</SimId>
      <InternalId>37</InternalId>
      <Name>RequestResponseFreeWorkstation</Name>
      <Type>RequestResponse</Type>
      <Source>3</Source>
      <Destination>4</Destination>
    </Message>
    <Message>
      <SimId>1014</SimId>
      <InternalId>38</InternalId>
      <Name>RequestResponseMoveWorker</Name>
      <Type>RequestResponse</Type>
      <Source>3</Source>
      <Destination>5</Destination>
    </Message>
    <Message>
      <SimId>1015</SimId>
      <InternalId>39</InternalId>
      <Name>RequestResponseWorkAgentA</Name>
      <Type>RequestResponse</Type>
      <Source>6</Source>
      <Destination>7</Destination>
    </Message>
    <Message>
      <SimId>1016</SimId>
      <InternalId>40</InternalId>
      <Name>RequestResponseWorkOnOrderWorkplace</Name>
      <Type>RequestResponse</Type>
      <Source>3</Source>
      <Destination>6</Destination>
    </Message>
    <Message>
      <InternalId>43</InternalId>
      <Type>StartFinish</Type>
      <Source>5</Source>
      <Destination>42</Destination>
    </Message>
    <Message>
      <SimId>1017</SimId>
      <InternalId>45</InternalId>
      <Name>RequestResponseOrderFreeWorkstation</Name>
      <Type>RequestResponse</Type>
      <Source>6</Source>
      <Destination>3</Destination>
    </Message>
    <Message>
      <SimId>1018</SimId>
      <InternalId>46</InternalId>
      <Name>RequestResponseWorkerFreeWorkstation</Name>
      <Type>RequestResponse</Type>
      <Source>7</Source>
      <Destination>6</Destination>
    </Message>
    <Message>
      <InternalId>48</InternalId>
      <Type>StartFinish</Type>
      <Source>5</Source>
      <Destination>47</Destination>
    </Message>
    <Message>
      <InternalId>50</InternalId>
      <Type>StartFinish</Type>
      <Source>7</Source>
      <Destination>49</Destination>
    </Message>
    <Message>
      <InternalId>52</InternalId>
      <Type>StartFinish</Type>
      <Source>7</Source>
      <Destination>51</Destination>
    </Message>
    <Message>
      <SimId>1019</SimId>
      <InternalId>53</InternalId>
      <Name>RequestResponseMoveWorker</Name>
      <Type>RequestResponse</Type>
      <Source>7</Source>
      <Destination>6</Destination>
    </Message>
    <Message>
      <InternalId>55</InternalId>
      <Type>Parent</Type>
      <Source>1</Source>
      <Destination>2</Destination>
    </Message>
    <Message>
      <InternalId>56</InternalId>
      <Type>Parent</Type>
      <Source>3</Source>
      <Destination>2</Destination>
    </Message>
    <Message>
      <InternalId>57</InternalId>
      <Type>Parent</Type>
      <Source>4</Source>
      <Destination>3</Destination>
    </Message>
    <Message>
      <InternalId>58</InternalId>
      <Type>Parent</Type>
      <Source>5</Source>
      <Destination>3</Destination>
    </Message>
    <Message>
      <InternalId>59</InternalId>
      <Type>Parent</Type>
      <Source>6</Source>
      <Destination>3</Destination>
    </Message>
    <Message>
      <InternalId>60</InternalId>
      <Type>Parent</Type>
      <Source>7</Source>
      <Destination>6</Destination>
    </Message>
    <Message>
      <InternalId>62</InternalId>
      <Type>Parent</Type>
      <Source>61</Source>
      <Destination>6</Destination>
    </Message>
    <Message>
      <SimId>1020</SimId>
      <InternalId>63</InternalId>
      <Name>RequestResponseWorkAgentB</Name>
      <Type>RequestResponse</Type>
      <Source>6</Source>
      <Destination>61</Destination>
    </Message>
  </Messages>
  <IID>74</IID>
</ABAsim>
